/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-16 00:04:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepageProject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import co.kh.dev.homepageproject.model.MemberDAO;
import co.kh.dev.homepageproject.model.MemberVO;
import co.kh.dev.homepageproject.model.BoardMemberDAO;
import co.kh.dev.homepageproject.model.BoardMemberVO;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import co.kh.dev.homepageproject.model.BoardMemberDAO;
import co.kh.dev.homepageproject.model.BoardMemberVO;
import java.text.SimpleDateFormat;
import co.kh.dev.homepageproject.model.BoardMemberDAO;
import co.kh.dev.homepageproject.model.BoardMemberVO;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/homepageProject/regForm.jsp", Long.valueOf(1734247620000L));
    _jspx_dependants.put("/homepageProject/loginComplete.jsp", Long.valueOf(1734244025000L));
    _jspx_dependants.put("/homepageProject/content.jsp", Long.valueOf(1734278251000L));
    _jspx_dependants.put("/homepageProject/tableMenu.jsp", Long.valueOf(1734274248000L));
    _jspx_dependants.put("/homepageProject/memberChange.jsp", Long.valueOf(1734248277000L));
    _jspx_dependants.put("/homepageProject/updateForm.jsp", Long.valueOf(1734278326000L));
    _jspx_dependants.put("/homepageProject/loginMenu.jsp", Long.valueOf(1734242140000L));
    _jspx_dependants.put("/homepageProject/writeForm.jsp", Long.valueOf(1734307462117L));
    _jspx_dependants.put("/homepageProject/deleteForm.jsp", Long.valueOf(1734270041000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("co.kh.dev.homepageproject.model.MemberVO");
    _jspx_imports_classes.add("co.kh.dev.homepageproject.model.BoardMemberDAO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("co.kh.dev.homepageproject.model.BoardMemberVO");
    _jspx_imports_classes.add("co.kh.dev.homepageproject.model.MemberDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	//메인페이지 가운데 페이지 전환플래그
	String flag = request.getParameter("flag");
	if(flag == null){
		flag = "none";
	}
	String tableflag = request.getParameter("tableflag");
	if(tableflag == null){
		tableflag = "none";
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/homepage.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"css/regform.css\" type=\"text/css\">\r\n");
      out.write("<script language=\"javascript\" src=\"js/hompage.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/regform.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/de7b35df6f.js\" async\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"carousel(); inputCheck(); inputCheck2();\">\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<p>\r\n");
      out.write("			<i class=\"fa-solid fa-house\"></i> 개인웹사이트\r\n");
      out.write("		</p>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li class=\"dropdown\"><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("				<div class=\"dropdown-content\">\r\n");
      out.write("					<a href=\"#\">select</a> <a href=\"#\">select</a> <a href=\"#\">select</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li class=\"dropdown\"><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("				<div class=\"dropdown-content\">\r\n");
      out.write("					<a href=\"#\">select</a> <a href=\"#\">select</a> <a href=\"#\">select</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li class=\"dropdown\"><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("				<div class=\"dropdown-content\">\r\n");
      out.write("					<a href=\"#\">select</a> <a href=\"#\">select</a> <a href=\"#\">select</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li class=\"dropdown\"><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("				<div class=\"dropdown-content\">\r\n");
      out.write("					<a href=\"#\">select</a> <a href=\"#\">select</a> <a href=\"#\">select</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<p>\r\n");
      out.write("			<a href=\"\"><i class=\"fa-brands fa-facebook\"></i></a> <a href=\"\"><i\r\n");
      out.write("				class=\"fa-solid fa-dove\"></i></a>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"slideshow\">\r\n");
      out.write("		<div class=\"slideshow_slides\">\r\n");
      out.write("			<a href=\"#\"><img src=\"/images/slide-1.jpg\" alt=\"\"></a> \r\n");
      out.write("			<a href=\"#\"><img src=\"/images/slide-2.jpg\" alt=\"\"></a> \r\n");
      out.write("			<a href=\"#\"><img src=\"/images/slide-3.jpg\" alt=\"\"></a> \r\n");
      out.write("			<a href=\"#\"><img src=\"/images/slide-4.jpg\" alt=\"\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"slideshow_nav\">\r\n");
      out.write("			<a href=\"#\" class=\"prev\"><i\r\n");
      out.write("				class=\"fa-solid fa-circle-chevron-left\"></i></a> <a href=\"#\"\r\n");
      out.write("				class=\"next\"><i class=\"fa-solid fa-circle-chevron-right\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"shlideshow_indicator\">\r\n");
      out.write("			<a href=\"#\" class=\"active\"><i class=\"fa-solid fa-circle-dot\"></i></a>\r\n");
      out.write("			<a href=\"#\"><i class=\"fa-solid fa-circle-dot\"></i></a> <a href=\"#\"><i\r\n");
      out.write("				class=\"fa-solid fa-circle-dot\"></i></a> <a href=\"#\"><i\r\n");
      out.write("				class=\"fa-solid fa-circle-dot\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"tbody\">\r\n");
      out.write("		<div class=\"left\">\r\n");
      out.write("			공지사항\r\n");
      out.write("			<div class=\"left1\"></div>\r\n");
      out.write("			<div class=\"left2\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("<!-- 		가운데 -->\r\n");
      out.write("		<div class=\"center\">\r\n");
 
		  	//회원가입 화면을 띄운다
				if(flag.equals("regform")){

      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("	<main >\r\n");
      out.write("		<form method=\"post\" action=\"regProc.jsp\" name=\"regForm\" class=\"myform\">\r\n");
      out.write("			<table border=\"1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td  class=\"login_table\" colspan=\"2\" align=\"center\">회원 가입 정보 입력</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>아이디</td>\r\n");
      out.write("					<td align=\"left\">\r\n");
      out.write("						&nbsp;&nbsp;<input id=\"input-id\" type=\"text\" name=\"id\" required /><span></span>&nbsp; \r\n");
      out.write("						<br>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"button\" value=\"중복확인\" onClick=\"idCheck(this.form.id.value)\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>패스워드</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-pw1\" type=\"password\" name=\"pass\" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td >패스워드 확인</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-pw2\" type=\"password\" name=\"repass\" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이름</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-name\" type=\"text\" name=\"name\" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>전화번호</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-tel\"  type=\"tel\" name=\"tel\" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이메일</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input  id=\"input-email\"  type=\"text\" name=\"email\" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>우편번호</td>\r\n");
      out.write("					<td align=\"left\">\r\n");
      out.write("						&nbsp;&nbsp;<input  id=\"zipcode\"  type=\"text\" name=\"zipcode\" required /> \r\n");
      out.write("						<br>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"button\" value=\"찾기\" onClick=\"zipCheck()\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소1</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input  id=\"addr1\" type=\"text\" name=\"address1\" size=\"50\" required /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소2</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"addr2\" type=\"text\" name=\"address2\" size=\"30\" required /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\">\r\n");
      out.write("						<input type=\"submit\" value=\"회원가입\"/>&nbsp;&nbsp; \r\n");
      out.write("						<input type=\"reset\" value=\"다시입력\" />&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" onclick=\"location.href = 'mainPage.jsp?flag=none'\" value=\"뒤로가기\"> \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</main>\r\n");
      out.write("<!-- </body>\r\n");
      out.write("</html> -->");
      out.write('\r');
      out.write('\n');
			//회원정보변경화면을 메인에 띄운다
				}else if(flag.equals("memberChange")){ 

      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = (String) session.getAttribute("id");
MemberVO mvo = new MemberVO();
mvo.setId(id);
MemberDAO mdao = MemberDAO.getInstance();
mvo = mdao.selectOneDB(mvo);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("		<form method=\"post\" action=\"memberChangeDB.jsp\" name=\"regForm\" class=\"myform2\" onsubmit=\"return checkForm2()\">\r\n");
      out.write("			<input type=\"hidden\" name=\"id\" value=\"");
      out.print(id );
      out.write("\" />\r\n");
      out.write("			<table border=\"1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td  class=\"login_table\" colspan=\"2\" align=\"center\">회원 정보 변경</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>아이디</td>\r\n");
      out.write("					<td align=\"left\">\r\n");
      out.write("						&nbsp;&nbsp;");
      out.print(mvo.getId());
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>패스워드</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-pw12\" type=\"password\" name=\"pass\" value=");
      out.print(mvo.getPass() );
      out.write(" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>패스워드 확인</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-pw22\" type=\"password\" name=\"repass\" value=");
      out.print(mvo.getPass() );
      out.write(" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이름</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-name2\" type=\"text\" name=\"name\" value=");
      out.print(mvo.getName() );
      out.write(" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>전화번호</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"input-tel2\"  type=\"tel\" name=\"tel\" value=");
      out.print(mvo.getPhone() );
      out.write(" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이메일</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input  id=\"input-email2\"  type=\"text\" name=\"email\" value=");
      out.print(mvo.getEmail() );
      out.write(" required /><span></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>우편번호</td>\r\n");
      out.write("					<td align=\"left\">\r\n");
      out.write("						&nbsp;&nbsp;<input  id=\"zipcode2\"  type=\"text\" name=\"zipcode\" value=");
      out.print(mvo.getZipcode() );
      out.write(" required /> \r\n");
      out.write("						<br>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"button\" value=\"찾기\" onClick=\"zipCheck()\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소1</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input  id=\"addr12\" type=\"text\" name=\"address1\" value=");
      out.print(mvo.getAddress1() );
      out.write(" size=\"50\" required /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소2</td>\r\n");
      out.write("					<td align=\"left\">&nbsp;&nbsp;<input id=\"addr22\" type=\"text\" name=\"address2\" value=");
      out.print(mvo.getAddress2() );
      out.write(" size=\"30\" required /></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\">\r\n");
      out.write("						<input type=\"submit\" value=\"정보수정\"/>&nbsp;&nbsp; \r\n");
      out.write("						<input type=\"reset\" value=\"다시입력\" />&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" onclick=\"location.href = 'mainPage.jsp?flag=none'\" value=\"뒤로가기\"> \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</main>");
      out.write('\r');
      out.write('\n');
			//글목록 메인화면 
				} else if(tableflag.equals("none")){

      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// 1. 페이징기법 -  페이지 사이즈:1페이지에 10개 보이기
int pageSize = 10;
// 2. 페이징기법 - 페이지번호 선택
request.setCharacterEncoding("utf-8");
String pageNum = request.getParameter("pageNum");
if (pageNum == null) {
	pageNum = "1";
}
//3. 현재페이지 설정, start, end 
int currentPage = Integer.parseInt(pageNum);
int start = (currentPage - 1) * pageSize + 1; //4페이지 시작보여줘		(4-1)*10+1=>31
int end = (currentPage - 1) * pageSize + 10; //4페이지 끝번호 보여줘 4*10 =>40

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

      out.write('\r');
      out.write('\n');

//4. 해당된 페이지 10개를 가져온다
int number = 0;
ArrayList<BoardMemberVO> BoardMemberList = null;
BoardMemberDAO bdao = BoardMemberDAO.getInstance();

int count = bdao.selectCountDB();//전체 글수
if (count > 0) {
	//현재페이지 내용 10개만 가져온다
	BoardMemberList = bdao.selectStartEndDB(start, end);
}
//5. 만약 4페이지를 가져왔다면(31~40)을 가져왔따면 NUMBER = 40 전체객수 100 1페이지(100~91) 2페이지(90~81)
number = count - (currentPage - 1) * pageSize;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<b>글목록(전체 글:");
      out.print(count);
      out.write(")\r\n");
      out.write("		</b>\r\n");
      out.write("		<table width=\"700\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\"><a\r\n");
      out.write("					href=\"mainPage.jsp?tableflag=write\">글쓰기</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		");

		if (count == 0) {
		
      out.write("\r\n");
      out.write("		<table width=\"700\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">게시판에 저장된 글이 없습니다.</td>\r\n");
      out.write("		</table>\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<table border=\"1\" width=\"700\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("			align=\"center\">\r\n");
      out.write("			<tr height=\"30\">\r\n");
      out.write("				<td align=\"center\" width=\"50\">번 호</td>\r\n");
      out.write("				<td align=\"center\" width=\"250\">제 목</td>\r\n");
      out.write("				<td align=\"center\" width=\"100\">작성자</td>\r\n");
      out.write("				<td align=\"center\" width=\"150\">작성일</td>\r\n");
      out.write("				<td align=\"center\" width=\"50\">조 회</td>\r\n");
      out.write("				<td align=\"center\" width=\"100\">IP</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			for (BoardMemberVO article : BoardMemberList) {
				
			
      out.write("\r\n");
      out.write("			<tr height=\"30\">\r\n");
      out.write("				<td align=\"center\" width=\"50\">");
      out.print(number--);
      out.write("</td>\r\n");
      out.write("				<td width=\"250\">\r\n");
      out.write("					<!-- 수정 <5> --> \r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<a href=\"mainPage.jsp?num=");
      out.print(article.getNum());
      out.write("&pageNum=1&tableflag=select\"> \r\n");
      out.write("					<!-- 수정<6> -->\r\n");
      out.write("					");

					//6. depth 값에 따라서 5배수 증가를 해서 화면에 보여줘야한다
					//depth : 1 => 길이:5, 2=>10
					int wid = 0;
					if (article.getDepth() > 0) {
						wid = 5 * article.getDepth();
					
      out.write("\r\n");
      out.write("						<img src=\"img/level.gif\" width=\"");
      out.print(wid);
      out.write("\" height=\"16\">	<!-- 공백 -->\r\n");
      out.write("  					<img src=\"img/re.gif\">\r\n");
      out.write("						");

					}
						
      out.write("\r\n");
      out.write("						");
      out.print(article.getSubject());
      out.write("</a> \r\n");

 if (article.getReadcount() >= 20) {
 
      out.write(" <img src=\"img/hot.gif\" border=\"0\" height=\"16\"> \r\n");
      out.write(" ");

 }
 
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td align=\"center\" width=\"100\"><a\r\n");
      out.write("					href=\"mailto:");
      out.print(article.getEmail());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(article.getWriter());
      out.write("</a></td>\r\n");
      out.write("				<td align=\"center\" width=\"150\">");
      out.print(sdf.format(article.getRegdate()));
      out.write("</td>\r\n");
      out.write("				<td align=\"center\" width=\"50\">");
      out.print(article.getReadcount());
      out.write("</td>\r\n");
      out.write("				<td align=\"center\" width=\"100\">");
      out.print(article.getIp());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("		<!-- 수정 <7> -->\r\n");
      out.write("	</main>\r\n");
      out.write('\r');
      out.write('\n');
			//
				} else if(tableflag.equals("write")){

      out.write("\r\n");
      out.write("			");
      out.write('\n');

//새로운 글로 입력(num=0, ref=0, step=0, depth=0)
//부모글에 대한 답변으로 입력(num=부모값, ref=부모값, step=부모값, depth=부모값)
int num = 0, ref = 1, step = 0, depth = 0;
try {
	if (request.getParameter("num") != null) {
		num = Integer.parseInt(request.getParameter("num"));
		ref = Integer.parseInt(request.getParameter("ref"));
		step = Integer.parseInt(request.getParameter("step"));
		depth = Integer.parseInt(request.getParameter("depth"));
	}

      out.write("\n");
      out.write("	<main>\n");
      out.write("		<b>글쓰기</b>\n");
      out.write("\n");
      out.write("	<br></br>\n");
      out.write("	<form method=\"post\" name=\"writeForm\" action=\"writeProc.jsp\"	onsubmit=\"return writeSave()\">\n");
      out.write("		");
if(session.getAttribute("id")!=null){
      out.write("\n");
      out.write("				<input type=\"hidden\" size=\"30\" maxlength=\"30\" name=\"pass\" value=\"");
      out.print(session.getAttribute("pass"));
      out.write("\" />\n");
      out.write("		");
} 
      out.write("		\n");
      out.write("		<input type=\"hidden\" name=\"num\" value=\"");
      out.print(num);
      out.write("\"> \n");
      out.write("		<input type=\"hidden\" name=\"ref\" value=\"");
      out.print(ref);
      out.write("\"> \n");
      out.write("		<input type=\"hidden\" name=\"step\" value=\"");
      out.print(step);
      out.write("\"> \n");
      out.write("		<input type=\"hidden\" name=\"depth\" value=\"");
      out.print(depth);
      out.write("\">\n");
      out.write("		<table width=\"400\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n");
      out.write("			<tr>\n");
      out.write("				<td align=\"right\" colspan=\"2\"><a\n");
      out.write("					href=\"mainPage.jsp\">글목록</a></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td width=\"70\" align=\"center\">이름</td>\n");
      out.write("				<td width=\"330\"  align=\"left\" >\n");
      out.write("				");
if(session.getAttribute("id")!=null){
      out.write("\n");
      out.write("					<input type=\"hidden\" size=\"12\" maxlength=\"12\" name=\"writer\" value=\"");
      out.print(session.getAttribute("id"));
      out.write("\"/>\n");
      out.write("					");
      out.print(session.getAttribute("id"));
      out.write("\n");
      out.write("				");
}else{ 
      out.write("\n");
      out.write("					<input type=\"text\" size=\"12\" maxlength=\"12\" name=\"writer\" />\n");
      out.write("				");
} 
      out.write("\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td width=\"70\" align=\"center\">이메일</td>\n");
      out.write("				<td width=\"330\"  align=\"left\" >\n");
      out.write("				");
if(session.getAttribute("id")!=null){
      out.write("\n");
      out.write("						<input type=\"hidden\" size=\"30\" maxlength=\"30\" name=\"email\" value=\"");
      out.print(session.getAttribute("email"));
      out.write("\" />\n");
      out.write("				");
      out.print(session.getAttribute("email"));
      out.write("\n");
      out.write("				");
}else{ 
      out.write("\n");
      out.write("						<input type=\"text\" size=\"30\" maxlength=\"30\" name=\"email\" />\n");
      out.write("				");
} 
      out.write("		\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td width=\"70\" align=\"center\">제목</td>\n");
      out.write("				<td width=\"330\">\n");

					if (request.getParameter("num") == null) {

      out.write(" 				<input type=\"text\" size=\"50\" maxlength=\"50\" name=\"subject\" /> \n");

 						} else {

      out.write(" \n");
      out.write(" 					<input type=\"text\" size=\"50\" maxlength=\"50\" name=\"subject\" value=\"[답변]\" />\n");

					}

      out.write("\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td width=\"70\" align=\"center\">내용</td>\n");
      out.write("				<td width=\"330\"><textarea name=\"content\" rows=\"13\" cols=\"50\"></textarea>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			");
if(session.getAttribute("id")==null){
      out.write("\n");
      out.write("			<tr>\n");
      out.write("				<td width=\"70\" align=\"center\">비밀번호</td>\n");
      out.write("				<td width=\"330\" align=\"left\" >\n");
      out.write("					<input type=\"password\" size=\"10\" maxlength=\"10\" name=\"pass\" />\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			");
} 
      out.write("\n");
      out.write("			<tr>\n");
      out.write("				<td colspan=\"2\" align=\"center\"><input\n");
      out.write("					type=\"submit\" value=\"글쓰기\" /> <input type=\"reset\" value=\"다시작성\" />\n");
      out.write("					<input type=\"button\" value=\"목록\"\n");
      out.write("					onClick=\"window.location='mainPage.jsp'\"></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("		</main>\n");
      out.write("	");

	} catch (Exception e) {
	}
	
      out.write('\n');
      out.write('\r');
      out.write('\n');

				} else if(tableflag.equals("select")){

      out.write("\r\n");
      out.write("			");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	request.setCharacterEncoding("UTF-8");
	int num = Integer.parseInt(request.getParameter("num"));
	String pageNum = request.getParameter("pageNum");
	BoardMemberVO vo = new BoardMemberVO();
	vo.setNum(num);
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

      out.write('\n');

try{
BoardMemberDAO bdao = BoardMemberDAO.getInstance();
BoardMemberVO bvo =  bdao.selectBoardMemberDB(vo);
int _num = vo.getNum();
int ref=bvo.getRef();
int step=bvo.getStep();
int depth=bvo.getDepth();

      out.write("\n");
      out.write("	<main>\n");
      out.write("		<b>글내용 보기</b> <br></br>\n");
      out.write("		<form>\n");
      out.write("			<table width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\"\n");
      out.write("				 align=\"center\">\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=\"center\" width=\"125\">글번호</td>\n");
      out.write("					<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(bvo.getNum());
      out.write("</td>\n");
      out.write("					<td align=\"center\" width=\"125\">조회수</td>\n");
      out.write("					<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(bvo.getReadcount());
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=\"center\" width=\"125\">작성자</td>\n");
      out.write("					<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(bvo.getWriter());
      out.write("</td>\n");
      out.write("					<td align=\"center\" width=\"125\">작성일</td>\n");
      out.write("					<td align=\"center\" width=\"125\" align=\"center\">");
      out.print( sdf.format(bvo.getRegdate()));
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=\"center\" width=\"125\">글제목</td>\n");
      out.write("					<td align=\"center\" width=\"375\" align=\"center\" colspan=\"3\">");
      out.print(bvo.getSubject());
      out.write("</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td align=\"center\" width=\"125\">글내용</td>\n");
      out.write("					<td align=\"left\" width=\"375\" colspan=\"3\"><pre>");
      out.print(bvo.getContent());
      out.write("</pre></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td colspan=\"4\" align=\"right\">\n");
      out.write("					<input\n");
      out.write("						type=\"button\" value=\"글수정\"\n");
      out.write("						onclick=\"document.location.href='mainPage.jsp?num=");
      out.print(_num);
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("&tableflag=update'\">\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp; \n");
      out.write("						<input type=\"button\" value=\"글삭제\"\n");
      out.write("						onclick=\"document.location.href='mainPage.jsp?num=");
      out.print(_num);
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("&tableflag=delete'\">\n");
      out.write("						&nbsp;&nbsp;&nbsp;&nbsp; <!-- 수정<1> --> \n");
      out.write("						<input type=\"button\" value=\"글목록\" onclick=\"document.location.href='mainPage.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	</main>\n");
      out.write("			");

 }catch(Exception e){e.printStackTrace();} 

      out.write('\n');
      out.write('\r');
      out.write('\n');

				} else if(tableflag.equals("update")){

      out.write("\r\n");
      out.write("			");
      out.write('\n');
      out.write('\n');
      out.write('\n');

request.setCharacterEncoding("utf-8");
int num = Integer.parseInt(request.getParameter("num"));
String pageNum = request.getParameter("pageNum");
BoardMemberVO vo = new BoardMemberVO();
vo.setNum(num);

      out.write('\n');

try {
	BoardMemberDAO bdao = BoardMemberDAO.getInstance();
	BoardMemberVO article = bdao.selectBoardMemberOneDB(vo);

      out.write("\n");
      out.write("	<main>\n");
      out.write("		<b>글수정</b> <br>\n");
      out.write("		<form method=\"post\" name=\"writeform\" action=\"updateProc.jsp?pageNum=");
      out.print(pageNum);
      out.write("\" onsubmit=\"return writeSave()\">\n");
      out.write("			<input type=\"hidden\" name=\"num\" value=\"");
      out.print(article.getNum());
      out.write("\">\n");
      out.write("			\n");
      out.write("			<table width=\"400\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\"\n");
      out.write("				 align=\"center\">\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"70\" align=\"center\">이 름</td>\n");
      out.write("					<td align=\"left\" width=\"330\"><input type=\"text\" size=\"10\"\n");
      out.write("						maxlength=\"10\" name=\"writer\" value=\"");
      out.print(article.getWriter());
      out.write("\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"70\" align=\"center\">제 목</td>\n");
      out.write("					<td align=\"left\" width=\"330\"><input type=\"text\" size=\"40\"\n");
      out.write("						maxlength=\"50\" name=\"subject\" value=\"");
      out.print(article.getSubject());
      out.write("\"></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"70\" align=\"center\">Email</td>\n");
      out.write("					<td align=\"left\" width=\"330\"><input type=\"text\" size=\"40\"\n");
      out.write("						maxlength=\"30\" name=\"email\" value=\"");
      out.print(article.getEmail());
      out.write("\"></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"70\" align=\"center\">내 용</td>\n");
      out.write("					<td align=\"left\" width=\"330\"><textarea name=\"content\"\n");
      out.write("							rows=\"13\" cols=\"40\">\n");
      out.write("        ");
      out.print(article.getContent());
      out.write("</textarea></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"70\" align=\"center\">비밀번호</td>\n");
      out.write("					<td align=\"left\" width=\"330\"><input type=\"password\" size=\"8\"\n");
      out.write("						maxlength=\"12\" name=\"pass\"></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td colspan=2 align=\"center\">\n");
      out.write("						<input type=\"submit\" value=\"글수정\"> \n");
      out.write("						<input type=\"reset\"	value=\"다시작성\"> \n");
      out.write("						<input type=\"button\" value=\"목록보기\" onclick=\"document.location.href='mainPage.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	</main>\n");
      out.write("	");

	} catch (Exception e) {
	}
	
      out.write('\n');
      out.write('\n');
      out.write('\r');
      out.write('\n');

				}  else if(tableflag.equals("delete")){

      out.write("\r\n");
      out.write("			");
      out.write('\n');

request.setCharacterEncoding("utf-8");
int num = Integer.parseInt(request.getParameter("num"));
String pageNum = request.getParameter("pageNum");

      out.write("\n");
      out.write("\n");
      out.write("	<main>\n");
      out.write("		<b>글삭제</b> <br></br>\n");
      out.write("		<form method=\"POST\" name=\"delForm\" action=\"deleteProc.jsp?pageNum=");
      out.print(pageNum);
      out.write("\" onsubmit=\"return deleteSave()\">\n");
      out.write("			<input type=\"hidden\" name=\"num\"	value=\"");
      out.print(num);
      out.write("\">\n");
      out.write("			<table border=\"1\" align=\"center\" cellspacing=\"0\" cellpadding=\"0\" width=\"360\">\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=center><b>비밀번호를 입력해 주세요.</b></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=center>비밀번호 : \n");
      out.write("					<input type=\"password\" name=\"pass\"	size=\"8\" maxlength=\"12\"> \n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr height=\"30\">\n");
      out.write("					<td align=center>\n");
      out.write("						<input type=\"submit\" value=\"글삭제\"> \n");
      out.write("						<input type=\"button\" value=\"글목록\" onclick=\"document.location.href= 'mainPage.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	</main>\n");
      out.write('\r');
      out.write('\n');

				}  

      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("<!-- 		오른쪽 -->\r\n");
      out.write("		<div class=\"right\">\r\n");
      out.write("			로그인창\r\n");
      out.write("			<div class=\"login\">\r\n");
      out.write("			");
 if(session.getAttribute("id") == null){ 
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"loginCheck.jsp\">\r\n");
      out.write("	<div class=\"login_block\">\r\n");
      out.write("		<table width=\"200\" id=\"login_table\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th class=\"login_input\">아이디</th>\r\n");
      out.write("				<td><input type=\"text\" name=\"id\" required></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th class=\"login_input\">비번</th>\r\n");
      out.write("				<td><input type=\"password\" name=\"pass\" required></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<br>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<input type=\"button\" onclick=\"location.href = 'mainPage.jsp?flag=regform'\" value=\"회원가입\"> \r\n");
      out.write("	<input type=\"submit\" value=\"로그인\"> \r\n");
      out.write("	<input type=\"button\" onclick=\"location.href = 'find_member.jsp'\" value=\"아이디찾기\">\r\n");
      out.write("</form>");
      out.write("\r\n");
      out.write("			");
}else if(session != null){
      out.write("\r\n");
      out.write("			");
      out.write('\r');
      out.write('\n');
 String name = (String)session.getAttribute("name"); 
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"loginCheck.jsp\">\r\n");
      out.write("	<div class=\"login_block\">\r\n");
      out.write("		<table width=\"200\" id=\"login_table\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print(name);
      out.write("님 방문을 환영합니다</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<br>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<input type=\"button\" onclick=\"location.href = 'logout.jsp'\" value=\"로그아웃\"> \r\n");
      out.write("	<input type=\"button\" onclick=\"location.href = 'mainPage.jsp?flag=memberChange'\" value=\"회원정보수정\">\r\n");
      out.write("	<input type=\"button\" onclick=\"location.href = '#'\" value=\"마이페이지\">\r\n");
      out.write("</form>");
      out.write("\r\n");
      out.write("			");
}
      out.write("		\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
